import { LocaleTypes } from "@/types";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const lang: Record<LocaleTypes, any> = {
  uz: {
    sidebar: {
      home: 'Asosiy',
      suppliers: 'Yetkazib beruvchilar',
      users: 'Hodimlar',
      search: 'Qidiruv',
      extranet: 'Extranet',
      orders: 'Buyurtmalar',
      contracts: 'Shartnomalar',
      community: 'Jamoa',
      reports: 'Hisobotlar',
      settings: 'Sozlamalar',
      currency: 'Valyuta kursi',
      rules: 'Qoidalar',
      basicIndicators: "Asosiy ko'rsatkichlar",
      routeReceipt: "Yo'nalish kvitansiyasi",
      personalization: 'Shaxsiylashtirish',
      ftp: 'FTP',
      rulesList: "Qoidalar ro'yixati",
      groups: 'Guruhlar',
      usageHistory: 'Foydalanish tarixi',
      charters: 'Charterlar',
      excursion: 'Ekskursiya',
      backToHome: 'Bosh sahifaga qaytish',
      title: 'Menyu',
      logout: 'Chiqish',
      files: 'Fayllar',
      back: 'Ortga qaytish',
    },
    pagination: "Ko'rsatish",
    empty_options: "Mavjud variantlar yo'q",
    currency: 'Valyuta',
    language: 'Til',
    select_all: 'Barchasini tanlash',
    empty_text: "Mavjud variantlar yo'q",
    search: 'Qidirish',
    payment: {
      title: "To'lov turini tanlang",
      balance: 'Shartnoma balansi',
      supplier: 'Поставщик',
      agree: "To'lovni tasdiqlashdan avval o'qib chiqing",
      public_offer: 'offertani',
      cancel: 'Yopish',
      confirm: 'Tasdiqlash',
      deposit: 'Depozit',
      card: 'Kredit karta',
      wallet: 'Hamyon',
    },
    tabs: {
      more: 'Yana',
    },
  },
  ru: {
    sidebar: {
      home: 'Главная',
      suppliers: 'Поставщики',
      users: 'Пользователи',
      search: 'Поиск',
      extranet: 'Экстранет',
      orders: 'Заказы',
      contracts: 'Договора',
      community: 'Сообщество',
      reports: 'Отчёты',
      settings: 'Настройки',
      currency: 'Курс валют',
      rules: 'Правила',
      basicIndicators: 'Основные показатели',
      routeReceipt: 'Квитанция маршрута',
      personalization: 'Персонализация',
      ftp: 'FTP',
      rulesList: 'Список правил',
      groups: 'Группы',
      usageHistory: 'История использования',
      charters: 'Чартеры',
      excursion: 'Экскурсия',
      files: "Файлы",
      backToHome: 'Вернуться на главную',
      title: 'Меню',
      logout: 'Выйти',
      back: 'Вернуться назад',
    },
    pagination: 'Показать по',
    empty_options: 'Нет доступных вариантов',
    currency: 'Валюта',
    language: 'Язык',
    select_all: 'Выбрать все',
    empty_text: 'Нет совпадений',
    search: 'Поиск',
    payment: {
      title: 'Выберите способ оплаты',
      balance: 'Баланс договора',
      supplier: 'Поставщик',
      agree: 'Перед подтверждением оплаты, предварительно ознакомьтесь с',
      public_offer: 'Публичной оффертой',
      cancel: 'Отменить',
      confirm: 'Подтвердить',
      deposit: 'Депозит',
      card: 'Кредитная карта',
      wallet: 'Кошелек',
    },
    tabs: {
      more: 'Ещё',
    },
  },
  en: {
    sidebar: {
      home: 'Home',
      suppliers: 'Suppliers',
      users: 'Employees',
      search: 'Search',
      extranet: 'Extranet',
      orders: 'Orders',
      contracts: 'Contracts',
      community: 'Community',
      reports: 'Reports',
      basicIndicators: "Basic Indicators",
      settings: 'Settings',
      currency: 'Exchange Rate',
      rules: 'Rules',
      routeReceipt: 'Route Receipt',
      personalization: 'Personalization',
      ftp: 'FTP',
      rulesList: 'Rules List',
      groups: 'Groups',
      usageHistory: 'Usage History',
      charters: 'Charters',
      excursion: 'Excursion',
      backToHome: 'Back to Home',
      title: 'Menu',
      files: 'Files',
      logout: 'Logout',
      back: 'Back',
    },
    pagination: 'Show by',
    empty_options: 'No available options',
    currency: 'Currency',
    language: 'Language',
    select_all: 'Select all',
    empty_text: 'No matches',
    search: 'Search',
    payment: {
      title: 'Select payment method',
      balance: 'Contract balance',
      supplier: 'Supplier',
      agree: 'Before confirming the payment, please familiarize yourself with',
      public_offer: 'Public offer',
      cancel: 'Cancel',
      confirm: 'Confirm',
      deposit: 'Deposit',
      card: 'Credit card',
      wallet: 'Wallet',
    },
    tabs: {
      more: 'More',
    },
  },
}
